title: Services
'@extends':
        type: default

form:
    fields:
        tabs:
            type: tabs
            active: 1
            fields:
                services:
                    type: tab
                    title: THEME_X_CORPORATION.ADMIN.SERVICES.LABEL
                    fields:
                        header.services:
                            name: services
                            type: list
                            style: vertical
                            label: THEME_X_CORPORATION.ADMIN.SERVICES.LABEL
                            fields:
                                .title:
                                    type: text
                                    label: THEME_X_CORPORATION.ADMIN.SERVICES.TITLE.LABEL
                                    help: THEME_X_CORPORATION.ADMIN.SERVICES.TITLE.HELP
                                .description:
                                    type: textarea
                                    label: THEME_X_CORPORATION.ADMIN.SERVICES.DESCRIPTION.LABEL
                                    help: THEME_X_CORPORATION.ADMIN.SERVICES.DESCRIPTION.HELP
                                .url:
                                    type: text
                                    label: THEME_X_CORPORATION.ADMIN.SERVICES.URL.LABEL
                                    help: THEME_X_CORPORATION.ADMIN.SERVICES.URL.HELP
                                .image:
                                    type: filepicker
                                    preview_images: true
                                    acccept:
                                        - .png
                                        - .jpg
                                        - .gif
                                    label: THEME_X_CORPORATION.ADMIN.SERVICES.IMAGE.LABEL
                                    help: THEME_X_CORPORATION.ADMIN.SERVICES.IMAGE.HELP
